# Generated by Django 3.2.2 on 2021-05-07 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_items_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
    ]
